pixlee_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from pixlee_app.views import (
	DashboardView,
	get_status_view,
	LandingView,
	reboot_job_view,
	submit_job_view
)

urlpatterns = [
    	url(
		r'^admin/',
		 include(admin.site.urls)
	),
	url(
		r'^$',
		view=LandingView.as_view(),
		name='landing_view', 
	),
	url(
		r'^dashboard/$',
		view=DashboardView.as_view(),
		name='dashboard_view', 
	),
	url(
		r'^submit-job/$',
		view=submit_job_view,
		name='submit_job_view', 
	),
	url(
		r'^reboot-job/$',
		view=reboot_job_view,
		name='reboot_job_view', 
	),
	url(
		r'^get-status/$',
		view=get_status_view,
		name='get_status_view', 
	),
]

pixlee_app/models.py
import os, urllib

from django.core.files import File
from django.db import models


# Create your models here.
class Job(models.Model):

	tag = models.ForeignKey(
		to="pixlee_app.Tag",
		related_name="jobs",
	)
	
	from_date = models.DateField()
	to_date = models.DateField()
	
	image_count = models.IntegerField(default=0)
	checked_pages = models.IntegerField(default=0)
	last_max_tag_id = models.CharField(max_length=100, null=True, blank=True)
	last_modified_datetime = models.DateTimeField(auto_now=True, null=True, blank=True)

	job_start_datetime = models.DateTimeField(auto_now_add=True, null=True, blank=True)
	job_end_datetime = models.DateTimeField(null=True, blank=True)


class Tag(models.Model):
	
	name = models.CharField(max_length=50)


class InstagramContent(models.Model):
	
	tag_date = models.DateField()
	tag = models.ForeignKey(
		to="pixlee_app.Tag",
		related_name="instagram_content",
	)
	instagram_id = models.CharField(max_length=100)
	image_url = models.URLField()
	image_file = models.ImageField(upload_to='images', null=True, blank=True)

	def get_remote_image(self):

		if self.image_url and not self.image_file:
			result = urllib.urlretrieve(self.image_url)
			self.image_file.save(
				os.path.basename(self.image_url),
				File(open(result[0]))
			)
			self.save()
	

pixlee_app/forms.py
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Div, HTML

class SubmitJobForm(forms.Form):
	
	tag = forms.CharField(max_length=50, required=True)
	from_date = forms.DateField()
	to_date = forms.DateField()

	def __init__(self, *args, **kwargs):
		super(SubmitJobForm, self).__init__(*args, **kwargs)

		self.helper = FormHelper()
		self.helper.layout = Layout(
			Fieldset(
				"Job Form",
				"tag",
				"from_date",
				"to_date",
				HTML(
					'''
					<div class="form-group">
						<button type="button" class="btn btn-primary" onclick="submitJob()">
							<i class="fa fa-plus"></i> Submit
						</button>
					</div>
					'''
				),
			)
		)

pixlee_app/views.py
# Python
import json, sys, traceback
import datetime

# Django
from django.shortcuts import render
from django.views.generic import (
	ListView,
	RedirectView,
	TemplateView
)
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, JsonResponse

# Third Party
import pytz
import requests

# App
from .forms import SubmitJobForm
from .models import (
	InstagramContent,
	Job,
	Tag,
)


# ====================================================================================
# HELPERS
# ====================================================================================

def unix_to_date(unix_time):
    return datetime.datetime.fromtimestamp(
        int(unix_time)
    ).date()

# ====================================================================================
# VIEWS
# ====================================================================================

class DashboardView(TemplateView):

	template_name = "pixlee_app/base.html"

	def get_context_data(self, **kwargs):
		
		data = super(DashboardView, self).get_context_data(**kwargs)
		
		submit_job_form = SubmitJobForm()

		data.update({"submit_job_form": submit_job_form})

		return data

class LandingView(RedirectView):

	def get_redirect_url(self, *args, **kwargs):
		return (
			"https://instagram.com/oauth/authorize/"
			"?client_id=d64c4125fbb642e8ae41d9d8e696664a"
			"&redirect_uri=http%3A%2F%2Flocalhost%3A8000%2Fdashboard%2F&response_type=token"
		)

@csrf_exempt
def get_status_view(request):

	running_jobs = list(Job.objects.filter(
		job_end_datetime__isnull=True
	).values(
		"pk",
		"tag__name",
		"from_date",
		"to_date",
		"job_start_datetime",
		"job_end_datetime",
		"image_count",
		"checked_pages",
		"last_modified_datetime",
	).order_by(
		"-job_start_datetime"
	))

	# Only allow unresponsive jobs to be reset.
	# Assuming 10 seconds of no updates to be "unresponsive"
	right_now = datetime.datetime.now(pytz.utc)
	ten_seconds_ago = right_now - datetime.timedelta(seconds=10)
	for job in running_jobs:
		if job.get("last_modified_datetime") < ten_seconds_ago:
			job.update({"ok_to_reboot": 1})

	data = {
		"success": True,
		"jobs": running_jobs
	}

	return JsonResponse(
		data=data
	)

@csrf_exempt
def submit_job_view(request):

	submit_form = SubmitJobForm(
		data=request.POST
	)
	if submit_form.is_valid():

		try:
			tag, created = Tag.objects.update_or_create(
				name=request.POST.get("tag").lower()
			)

			job = Job.objects.create(
				tag=tag,
				from_date=submit_form.cleaned_data.get("from_date"),
				to_date=submit_form.cleaned_data.get("to_date"),
			)

			scan_tagged_content(
				job=job,
				access_token=request.POST.get("access_token"),
			)
		except:
			traceback.print_exc(file=sys.stdout)
	else:
		print submit_form.errors

	return JsonResponse(
		data={
			"success": True,
		}
	)

@csrf_exempt
def reboot_job_view(request):

	job = Job.objects.get(
		pk=request.POST.get("pk")
	)

	# Save job to update it's last_modified field
	job.save()

	access_token = request.POST.get("access_token")

	scan_tagged_content(job, access_token)

	return JsonResponse(
		data={
			"success": True,
		}
	)

def scan_tagged_content(job, access_token):

	base_url = "https://api.instagram.com/v1/tags/{tag}/media/recent".format(tag=job.tag.name)
	payload = {
		"access_token": access_token,
		"q": job.tag,
		"count": 35,  # The API seems to max out at 35 objects per page for the time being
	}

	# If job has last_max_tag_id, it means we're requesting to reboot a previously stopped job.
	# Update the payload to restart from where we left off
	if job.last_max_tag_id:
		payload.update({
		"max_tag_id": job.last_max_tag_id
	})

	continue_job = True
	while continue_job:

		r = requests.get(
			base_url,
			params=payload
		)

		# Break if we don't have a 200 success status
		if r.status_code != 200:
			continue_job = False
			break

		# Ensure we're still over our rate limit
		headers = r.headers
		try:
			rate_limit_remaining = int(headers.get("X-Ratelimit-Remaining"))
			if rate_limit_remaining <= 0:
				continue_job = False
		except TypeError:
			continue_job = False
			break

		# Iterate through each content object in page data
		page = json.loads(r.text)
		saved_image_count = job.image_count

		for content in page.get("data"):
			username = content.get("user").get("username")
			tag_date = get_tag_date(job.tag, username, content)

			# Skip if not photo
			if content.get("type") != "image":
				continue

			# Skip if no tag date found
			if not tag_date:
				continue
	
			# If tag_time is on or before job.from_date, we've gone too far in the past.
			# Stop the job
			if tag_date <= job.from_date:
				continue_job = False
				break
			
			# If tag_time is between from and to dates, populate content
			if job.from_date < tag_date < job.to_date:
				
				instagram_image = InstagramContent.objects.create(
					tag=job.tag,
					tag_date=tag_date,
					instagram_id=content.get("id"),
					image_url=content.get("images").get("thumbnail").get("url")
				)

				instagram_image.get_remote_image()

				saved_image_count += 1

		# If we're still within our job range, update max_id param and make new request
		next_max_tag_id = page.get("pagination").get("next_max_tag_id")
		payload.update({
			"max_tag_id": next_max_tag_id
		})

		# Update job
		job.last_max_tag_id = next_max_tag_id
		job.image_count = saved_image_count
		job.checked_pages += 1
		job.save()

	# End the job
	job.job_end_datetime = datetime.datetime.now()
	job.save()
		

def get_tag_date(tag, username, content):

	hashed_tag = "#" + tag.name
	tag_time = None

	# Find tag_time in caption
	caption = content.get("caption")
	if caption:
		tag_time = caption.get("created_time")

	# See if original poster put tag in comment
	comments = content.get("comments").get("data")
	if comments:
		try:
			original_poster_tag_comment = filter(
				lambda x: all([
					x.get("from").get("username") == username,
					hashed_tag in x.get("text")
				]),
				comments
			)[0]

			tag_time = original_poster_tag_comment.get("created_time")

		except IndexError:
			# Original poster did not have a comment with the tag in it.
			# Continue to use the caption created time
			pass

	# Convert time from unix time
	if tag_time:
		tag_date = unix_to_date(tag_time)
		return tag_date
	else:
		return None

pixlee_app/templates/pixlee_app/base.html
{% load crispy_forms_tags %}
{% load static %}
<!DOCTYPE HTML>
<html>
	<head>
		<title>Instagram Scraper</title>

		<script type="text/javascript" src="{% static "pixlee_app/bower_components/jquery/dist/jquery.min.js" %}"></script>
		<script type="text/javascript" src="{% static "pixlee_app/bower_components/moment/min/moment.min.js" %}"></script>
		<script type="text/javascript" src="{% static "pixlee_app/bower_components/bootstrap/dist/js/bootstrap.min.js" %}"></script>
		<script type="text/javascript" src="{% static "pixlee_app/bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js" %}"></script>
		<link rel="stylesheet" href="{% static "pixlee_app/bower_components/bootstrap/dist/css/bootstrap.min.css" %}" />
		<link rel="stylesheet" href="{% static "pixlee_app/bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css" %}" />

		<script type="text/javascript">

			
			// Initialize page
			var accessToken = null;

			$(document).ready(function(){

				// Datetime pickers
				$("#id_from_date").datetimepicker({
					format: 'YYYY-MM-DD',
					maxDate: moment()
				});
				$("#id_to_date").datetimepicker({
					format: 'YYYY-MM-DD',
					maxDate: moment().add(1, "days")
				});

				// Get access token from url fragment
				var frag = window.location.hash.substr(1);
				accessToken = frag.split("=")[1];				
				console.log(accessToken);

				// Start polling for status
				pollStatus();
			});


			// Polls the job and instagram api status every N seconds
			function pollStatus(){

				$.ajax(
				{
					type: "GET",
					dataType: "json",
					url: "{% url "get_status_view" %}",
					data: {
						access_token: accessToken,
					},
					beforeSend:function(){
					},
					success:function(response){
						
						var jobs = response.jobs;
						var tbody = $("#job-table tbody");
						tbody.empty();

						for(job in jobs){

							var tag = jobs[job]["tag__name"];
							var from_date = jobs[job]["from_date"];
							var to_date = jobs[job]["to_date"];
							var started_datetime = jobs[job]["job_start_datetime"];
							var checked_pages = jobs[job]["checked_pages"];
							var image_count = jobs[job]["image_count"];
							var job_pk = jobs[job]["pk"];

							// Special case for rebooting
							var ok_to_reboot = jobs[job]["ok_to_reboot"];
							var button_text = "";
							if(ok_to_reboot === 1){
								button_text = "<button type='button' id='button-" + job_pk + "' onclick='rebootJob(" + job_pk +")'>Reboot Job</button>";
							}
							
							tbody.append(
								"<tr><td>" + tag + "</td><td>" + from_date + 
								"</td><td>" + to_date + "</td><td>" + started_datetime + 
								"</td><td>" + checked_pages + "</td><td>" + image_count +
								"</td><td>" + button_text +
								"</td></tr>"
							);
						}
					},
					error:function(xhr, ajaxOptions, thrownError){
					}
				});

				setTimeout("pollStatus()", 3000);
			};


			// Submits the job data entered by the user in the form
			function submitJob(){

				$.ajax(
				{
					type: "POST",
					dataType: "json",
					url: "{% url "submit_job_view" %}",
					data: {
						tag: $("#id_tag").val(),
						to_date: $("#id_to_date").val(),
						from_date: $("#id_from_date").val(),
						access_token: accessToken,
					},
					beforeSend:function(){
						// Empty the form
						$("form")[0].reset()
					},
					success:function(response){
						
					},
					error:function(xhr, ajaxOptions, thrownError){
						// Show field errors if applicable
					}
				});
			};

			// Reboot previously halted job
			function rebootJob(pk){

				$.ajax(
				{
					type: "POST",
					dataType: "json",
					url: "{% url "reboot_job_view" %}",
					data: {
						pk: pk,
						access_token: accessToken,
					},
					beforeSend:function(){
						var buttonId = "#button-" + pk;
						$(buttonId).remove();
					},
					success:function(response){
					},
					error:function(xhr, ajaxOptions, thrownError){
						// Show field errors if applicable
					}
				});
			};


		</script>
	</head>

	<body>

		<div class="container">
			<h1>Instagram Scraper</h1>

			<div class="row">
				<div class="col-sm-4">
					<div class="well">
						{% crispy submit_job_form %} 
					</div>
				</div>
				<div class="col-sm-8">
					<div class="well">
						<legend>Current Jobs</legend>
						<table class="table" id="job-table">
							<thead>
								<th>Tag</th>
								<th>From</th>
								<th>To</th>
								<th>Started Time</th>
								<th>Pages Checked</th>
								<th>Image Count</th>
								<th>Action</th>
							</thead>
							<tbody>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>

	</body>

</html>